"""Public API for exclusively estimating Morse potential parameters."""

from __future__ import annotations

import logging
from dataclasses import dataclass


@dataclass
class MorsePotentialParamsEstimate:
    """Estimated Morse potential params generated by neural network."""

    dissociation_energy: float
    """..."""

    equilibrium_bond_distance: float
    """..."""

    alpha: float
    """Controls the 'width' of the potential well."""


def estimate_morse_potential_params(
    level_energies: list[float],
) -> MorsePotentialParamsEstimate:
    """Estimate Morse potential params based on energies of up to 60 levels."""
    logging.info(level_energies)

    # Invoke neural network to estimate morse potential params.
    ...

    return MorsePotentialParamsEstimate(0.0, 0.0, 0.0)
