---
version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "daily"

      target-branch: "main"

      labels:
          - "dependencies"

      assignees:
          - "Argmaster"
          - "Ave44"
          - "MatSzpy"
          - "mateuszzalewski011"

      reviewers:
          - "Argmaster"
          - "Ave44"
          - "MatSzpy"
          - "mateuszzalewski011"
