extend = "../pyproject.toml"
ignore = [
    "S101",   # Assertions are OK in test code.
    "N802",   # Project names are used as test names thus causing conflicts with this rule.
    "INP001", # Ignore implicit namespaces.
    "D100",   # Missing docstring in public module
    "TCH002", # Move third-party import `mkdocs_macros.plugin.MacrosPlugin` into a type-checking block
    "D400",   # First line should end with a period
    "D401",   # First line of docstring should be in imperative mood: "This is the hook for defining variables, macros and filters"
    "D404",   # First word of the docstring should not be "This"
    "D415",   # First line should end with a period, question mark, or exclamation point
    "ANN202", # Missing return type annotation for private function `include_file`
    "ANN001", # Missing type annotation for function argument `filename`
    "PTH118", # `os.path.join()` should be replaced by `Path` with `/` operator
    "PTH123", # `open()` should be replaced by `Path.open()`
]
